using System; using System.Collections.Generic; using NUnit.Framework; using GeneralCore.Architecture; using GameplayCore.Damage; using GameplayCore.Entities; using ZombieWar.Features.Boss.Catalog; using ZombieWar.Features.Boss.Controller; using ZombieWar.Features.Boss.Domain; using ZombieWar.Features.Boss.Events; using ZombieWar.Features.Boss.Model; using ZombieWar.Features.Boss.Ports; using ZombieWar.Features.Boss.Registry; using ZombieWar.Features.Boss.Services; using ZombieWar.Features.Boss.Strategies;
namespace ZombieWar.Features.Boss.Tests
{
    public sealed class BossFeatureTests
    {
        private static BossDefinition Def(BossId id=BossId.BossA,float spawn=0f,float death=0f)=>new BossDefinition(id,100f,2f,360f,10f,2f,.2f,1f,.1f,spawn,.1f,.2f,1.5f,death,2f,1000,id==BossId.BossB?-3f:id==BossId.BossC?3f:0f,0f,0f);
        private static BossCatalog Catalog()=>new BossCatalog(new[]{Def(BossId.BossA),Def(BossId.BossB),Def(BossId.BossC)});
        [Test] public void Definition_Valid(){Assert.AreEqual(BossId.BossA,Def().Id);} [Test] public void Definition_Rejects_None(){Assert.Throws<ArgumentOutOfRangeException>(()=>Def(BossId.None));}
        [TestCase(0f)][TestCase(-1f)] public void Definition_Rejects_NonPositive_Health(float hp){Assert.Throws<ArgumentOutOfRangeException>(()=>new BossDefinition(BossId.BossA,hp,1,1,1,1,0,1,0,0,0,0,1,0,1,0,0,0,0));}
        [Test] public void Catalog_Has_All(){var c=Catalog();Assert.IsTrue(c.TryGet(BossId.BossA,out _));Assert.IsTrue(c.TryGet(BossId.BossB,out _));Assert.IsTrue(c.TryGet(BossId.BossC,out _));}
        [Test] public void Catalog_Rejects_Duplicate(){Assert.Throws<ArgumentException>(()=>new BossCatalog(new[]{Def(BossId.BossA),Def(BossId.BossA),Def(BossId.BossC)}));}
        [Test] public void Catalog_TryGet_None_Safe(){var c=Catalog();Assert.IsFalse(c.TryGet(BossId.None,out _));}
        [Test] public void Selection_One(){var s=new BossSpawnSelection(BossId.BossA);Assert.AreEqual(1,s.Count);Assert.AreEqual(BossId.BossA,s.First);}
        [Test] public void Selection_Two(){var s=new BossSpawnSelection(BossId.BossB,BossId.BossC);Assert.AreEqual(2,s.Count);Assert.AreEqual(BossId.BossC,s.Second);}
        [Test] public void Selection_Rejects_Duplicate(){Assert.Throws<ArgumentException>(()=>new BossSpawnSelection(BossId.BossA,BossId.BossA));}
        [Test] public void Plan_Rejects_Duplicate(){var p=new BossPoint(0,0,0);var a=new BossSpawnRequest(BossId.BossA,in p);Assert.Throws<ArgumentException>(()=>new BossSpawnPlan(in a,in a));}
        [Test] public void Runtime_Initial_Uninitialized(){Assert.IsFalse(new BossRuntime().IsInitialized);}
        [Test] public void Runtime_Initialize(){var r=new BossRuntime();r.Initialize(Catalog(),new FakeExecutor(),new ActiveBossRegistry());Assert.IsTrue(r.IsInitialized);}
        [Test] public void Runtime_Builds_A_At_Anchor(){var ex=new FakeExecutor();var r=new BossRuntime();r.Initialize(Catalog(),ex,new ActiveBossRegistry());var s=new BossSpawnSelection(BossId.BossA);var p=new BossPoint(10,0,5);Assert.IsTrue(r.TrySpawn(in s,in p));Assert.AreEqual(10f,ex.Plan.First.Position.X);}
        [Test] public void Runtime_Applies_BC_Offsets(){var ex=new FakeExecutor();var r=new BossRuntime();r.Initialize(Catalog(),ex,new ActiveBossRegistry());var s=new BossSpawnSelection(BossId.BossB,BossId.BossC);var p=new BossPoint(10,0,5);Assert.IsTrue(r.TrySpawn(in s,in p));Assert.AreEqual(7f,ex.Plan.First.Position.X);Assert.AreEqual(13f,ex.Plan.Second.Position.X);}
        [Test] public void Runtime_Shutdown(){var r=new BossRuntime();r.Initialize(Catalog(),new FakeExecutor(),new ActiveBossRegistry());r.Shutdown();Assert.IsFalse(r.IsInitialized);}
        [Test] public void ActiveRegistry_Add_Remove(){var e=new EventBus();var c=CreateController(e,out _,out _,out _,out _,out _,out _);var p=new BossPoint(0,0,0);var req=new BossSpawnRequest(BossId.BossA,in p);var d=Def();c.Activate(in d,in req);var r=new ActiveBossRegistry();Assert.IsTrue(r.Add(c));Assert.AreEqual(1,r.Count);Assert.IsTrue(r.Remove(c.EntityId));Assert.AreEqual(0,r.Count);}
        [Test] public void Controller_Activate_FullHealth(){var c=CreateController(new EventBus(),out var h,out _,out _,out _,out _,out _);Activate(c);Assert.AreEqual(100f,h.CurrentHealth);Assert.IsTrue(c.IsAlive);}
        [Test] public void Controller_Activate_Targetable(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _);Activate(c);Assert.IsTrue(c.IsTargetable);}
        [Test] public void Controller_Activate_FreshEntityId(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _);var first=Activate(c);c.Cancel();c.DeactivateForPool();var second=Activate(c);Assert.AreNotEqual(first.Value,second.Value);}
        [Test] public void Spawn_ZeroDuration_EntersChase(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _);Activate(c);Assert.AreEqual(BossStateId.Chase,c.State);}
        [Test] public void Chase_NoTarget_IsSafe(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _);Activate(c);Assert.DoesNotThrow(()=>c.Tick(.2f));}
        [Test] public void Chase_TargetInRange_EntersAttack(){var c=CreateController(new EventBus(),out _,out var target,out _,out _,out _,out _);target.Set(new BossPoint(1,0,0));Activate(c);c.Tick(.2f);Assert.AreEqual(BossStateId.Attack,c.State);}
        [Test] public void Attack_NoDamage_BeforeImpact(){var c=CreateController(new EventBus(),out _,out var target,out var attack,out _,out _,out _);target.Set(new BossPoint(1,0,0));Activate(c);c.Tick(.2f);c.Tick(.01f);Assert.AreEqual(0,attack.Count);}
        [Test] public void Attack_Impact_DamagesOnce(){var c=CreateController(new EventBus(),out _,out var target,out var attack,out _,out _,out _);target.Set(new BossPoint(1,0,0));Activate(c);c.Tick(.2f);c.Tick(.01f);c.NotifyAttackImpact();c.NotifyAttackImpact();Assert.AreEqual(1,attack.Count);}
        [Test] public void Attack_Impact_Paused_Ignored(){var c=CreateController(new EventBus(),out _,out var target,out var attack,out _,out _,out _);target.Set(new BossPoint(1,0,0));Activate(c);c.Tick(.2f);c.Tick(.01f);c.SetGameplayEnabled(false);c.NotifyAttackImpact();Assert.AreEqual(0,attack.Count);}
        [Test] public void NonLethalDamage_KeepsAlive(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _);Activate(c);c.ReceiveDamage(new DamageInfo(new EntityId(9),10,"test"));Assert.IsTrue(c.IsAlive);}
        [Test] public void LethalDamage_EntersDeath(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _);Activate(c);c.ReceiveDamage(new DamageInfo(new EntityId(9),100,"test"));Assert.AreEqual(BossStateId.Death,c.State);Assert.IsFalse(c.IsTargetable);}
        [Test] public void DefeatEvent_Once(){var e=new EventBus();int count=0;e.Subscribe<BossDefeatedEvent>(_=>count++);var c=CreateController(e,out _,out _,out _,out _,out _,out _);Activate(c);c.ReceiveDamage(new DamageInfo(new EntityId(9),100,"test"));c.ReceiveDamage(new DamageInfo(new EntityId(9),100,"test"));Assert.AreEqual(1,count);}
        [Test] public void DefeatEvent_PreservesKiller(){var e=new EventBus();EntityId killer=default;e.Subscribe<BossDefeatedEvent>(x=>killer=x.Killer);var c=CreateController(e,out _,out _,out _,out _,out _,out _);Activate(c);var k=new EntityId(77);c.ReceiveDamage(new DamageInfo(k,100,"test"));Assert.AreEqual(77,killer.Value);}
        [Test] public void Death_Unregisters_Target(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out var reg,out _);Activate(c);c.ReceiveDamage(new DamageInfo(new EntityId(1),100,"test"));Assert.AreEqual(1,reg.UnregisterCount);}
        [Test] public void Death_DisablesCollision(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out var view);Activate(c);c.ReceiveDamage(new DamageInfo(new EntityId(1),100,"test"));Assert.IsFalse(view.Collision);}
        [Test] public void Death_ReturnsPool(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _,out var pool);Activate(c);c.ReceiveDamage(new DamageInfo(new EntityId(1),100,"test"));Assert.AreEqual(1,pool.Count);}
        [Test] public void Cancel_DoesNotDefeat(){var e=new EventBus();int count=0;e.Subscribe<BossDefeatedEvent>(_=>count++);var c=CreateController(e,out _,out _,out _,out _,out _,out _);Activate(c);c.Cancel();Assert.AreEqual(0,count);}
        [Test] public void Cancel_ReturnsPool(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _,out var pool);Activate(c);c.Cancel();Assert.AreEqual(1,pool.Count);}
        [Test] public void Pause_StopsTickBehavior(){var c=CreateController(new EventBus(),out _,out var target,out _,out _,out _,out _);target.Set(new BossPoint(1,0,0));Activate(c);c.SetGameplayEnabled(false);c.Tick(1f);Assert.AreEqual(BossStateId.Chase,c.State);}
        [Test] public void Resume_Reenables(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _);Activate(c);c.SetGameplayEnabled(false);c.SetGameplayEnabled(true);Assert.IsTrue(c.GameplayEnabled);}
        [Test] public void Model_HitCooldown_Ticks(){var m=new BossModel();var d=Def();m.Activate(new EntityId(1),in d);m.BeginHitReactionCooldown();Assert.IsFalse(m.CanStartHitReaction);m.TickTimers(1f);Assert.IsTrue(m.CanStartHitReaction);}
        [Test] public void Point_Add(){var p=new BossPoint(1,2,3).Add(4,5,6);Assert.AreEqual(5,p.X);Assert.AreEqual(7,p.Y);Assert.AreEqual(9,p.Z);}
        [TestCase(0f,0f,3f,4f,25f)][TestCase(1f,1f,1f,1f,0f)] public void Point_DistanceXZ(float ax,float az,float bx,float bz,float expected){var a=new BossPoint(ax,0,az);var b=new BossPoint(bx,0,bz);Assert.AreEqual(expected,BossPoint.SqrDistanceXZ(in a,in b));}
        [Test] public void BasicStrategy_Delegates(){var a=new FakeAttack();var s=new BasicMeleeBossAttackStrategy(a);var r=new BossAttackRequest(new EntityId(1),new EntityId(2),3,BossAttackType.BasicMelee);Assert.IsTrue(s.TryExecute(in r));Assert.AreEqual(1,a.Count);}
        [Test] public void Runtime_TrySpawn_BeforeInitialize_False(){var r=new BossRuntime();var s=new BossSpawnSelection(BossId.BossA);var p=new BossPoint(0,0,0);Assert.IsFalse(r.TrySpawn(in s,in p));}
        [Test] public void Selection_Rejects_None(){Assert.Throws<ArgumentOutOfRangeException>(()=>new BossSpawnSelection(BossId.None));}
        [Test] public void Controller_Rejects_Definition_Request_Mismatch(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _);var d=Def(BossId.BossA);var p=new BossPoint(0,0,0);var r=new BossSpawnRequest(BossId.BossB,in p);Assert.Throws<ArgumentException>(()=>c.Activate(in d,in r));}
        [Test] public void Spawn_PositiveDuration_RemainsSpawn_UntilTick(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _);var d=Def(BossId.BossA,spawn:.5f);var p=new BossPoint(0,0,0);var r=new BossSpawnRequest(BossId.BossA,in p);c.Activate(in d,in r);Assert.AreEqual(BossStateId.Spawn,c.State);c.Tick(.6f);Assert.AreEqual(BossStateId.Chase,c.State);}
        [Test] public void Chase_TargetOutOfRange_RemainsChase(){var c=CreateController(new EventBus(),out _,out var target,out _,out _,out _,out _);target.Set(new BossPoint(100,0,0));Activate(c);c.Tick(.2f);Assert.AreEqual(BossStateId.Chase,c.State);}
        [Test] public void Attack_Timeout_NeverDamages(){var c=CreateController(new EventBus(),out _,out var target,out var attack,out _,out _,out _);target.Set(new BossPoint(1,0,0));Activate(c);c.Tick(.2f);c.Tick(.01f);c.Tick(2f);Assert.AreEqual(0,attack.Count);}
        [Test] public void Attack_TargetLost_ReturnsChase(){var c=CreateController(new EventBus(),out _,out var target,out _,out _,out _,out _);target.Set(new BossPoint(1,0,0));Activate(c);c.Tick(.2f);target.Clear();c.Tick(.2f);Assert.AreEqual(BossStateId.Chase,c.State);}
        [Test] public void NonLethalDamage_EntersHit_WhenAllowed(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _);Activate(c);c.ReceiveDamage(new DamageInfo(new EntityId(9),10,"test"));Assert.AreEqual(BossStateId.Hit,c.State);}
        [Test] public void DeactivateForPool_SetsInactive(){var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _);Activate(c);c.DeactivateForPool();Assert.AreEqual(BossStateId.Inactive,c.State);Assert.IsFalse(c.IsActive);}
        [Test] public void Registry_Rejects_Duplicate(){var e=new EventBus();var c=CreateController(e,out _,out _,out _,out _,out _,out _);Activate(c);var r=new ActiveBossRegistry();Assert.IsTrue(r.Add(c));Assert.IsFalse(r.Add(c));Assert.AreEqual(1,r.Count);}
        [Test] public void Runtime_Propagates_ExecutorFailure(){var ex=new FakeExecutor{Result=false};var r=new BossRuntime();r.Initialize(Catalog(),ex,new ActiveBossRegistry());var s=new BossSpawnSelection(BossId.BossA);var p=new BossPoint(0,0,0);Assert.IsFalse(r.TrySpawn(in s,in p));}
        [Test] public void Runtime_CancelAll_CancelsActiveBosses(){var registry=new ActiveBossRegistry();var c=CreateController(new EventBus(),out _,out _,out _,out _,out _,out _,out var pool);Activate(c);registry.Add(c);var r=new BossRuntime();r.Initialize(Catalog(),new FakeExecutor(),registry);r.CancelAll();Assert.AreEqual(1,pool.Count);}

        private static EntityId Activate(BossController c){var d=Def();var p=new BossPoint(0,0,0);var r=new BossSpawnRequest(BossId.BossA,in p);return c.Activate(in d,in r);}
        private static BossController CreateController(EventBus events,out FakeHealth health,out FakeTargetProvider targets,out FakeAttack attack,out FakeMotor motor,out FakeRegistration registration,out FakeView view){return CreateController(events,out health,out targets,out attack,out motor,out registration,out view,out _);}        
        private static BossController CreateController(EventBus events,out FakeHealth health,out FakeTargetProvider targets,out FakeAttack attack,out FakeMotor motor,out FakeRegistration registration,out FakeView view,out FakePool pool)
        {health=new FakeHealth();targets=new FakeTargetProvider();attack=new FakeAttack();motor=new FakeMotor();registration=new FakeRegistration();view=new FakeView();pool=new FakePool();return new BossController(new SequentialEntityIdGenerator(),new BossModel(),view,motor,health,targets,new BasicMeleeBossAttackStrategy(attack),registration,pool,NullBossFeedbackPort.Instance,events);}
        private sealed class FakeExecutor:IBossSpawnExecutor{public BossSpawnPlan Plan;public bool Result=true;public bool TrySpawnPlan(in BossSpawnPlan plan){Plan=plan;return Result;}}
        private sealed class FakeHealth:IBossHealthPort{public bool IsAlive=>CurrentHealth>0;public float CurrentHealth{get;private set;}public float MaxHealth{get;private set;}public void Initialize(EntityId id,float max){MaxHealth=max;CurrentHealth=max;}public void ApplyDamage(DamageInfo d){CurrentHealth-=d.Amount;if(CurrentHealth<0)CurrentHealth=0;}}
        private sealed class FakeTargetProvider:IBossTargetProvider{private bool _valid;private BossPoint _point;private readonly EntityId _id=new EntityId(2);public void Set(BossPoint p){_valid=true;_point=p;}public void Clear(){_valid=false;}public bool TryAcquireTarget(in BossPoint p,out BossTarget target){if(!_valid){target=BossTarget.None;return false;}target=BossTarget.From(_id,in _point);return true;}public bool TryGetTarget(EntityId id,out BossTarget target){if(!_valid||!id.Equals(_id)){target=BossTarget.None;return false;}target=BossTarget.From(_id,in _point);return true;}}
        private sealed class FakeAttack:IBossAttackPort{public int Count;public bool TryAttack(in BossAttackRequest r){Count++;return true;}}
        private sealed class FakeMotor:IBossMotor{public BossPoint Position{get;private set;}public float NormalizedSpeed{get;private set;}public void Warp(in BossPoint p)=>Position=p;public void SetEnabled(bool e){}public void MoveTowards(in BossPoint p,float s,float dt){Position=p;NormalizedSpeed=1;}public void Stop()=>NormalizedSpeed=0;}
        private sealed class FakeRegistration:IBossTargetRegistrationPort{public int RegisterCount,UnregisterCount;public void Register(EntityId id)=>RegisterCount++;public void Unregister(EntityId id)=>UnregisterCount++;}
        private sealed class FakePool:IBossPoolReturnPort{public int Count;public void Return(EntityId id,BossReleaseReason reason)=>Count++;}
        private sealed class FakeView:IBossView{public BossPoint Position{get;private set;}=new BossPoint(0,0,0);public bool Collision{get;private set;}public void ResetForReuse(){}public void SetActive(bool a){}public void SetScale(float s){}public void SetLocomotionSpeed(float s){}public void SetGameplayCollisionEnabled(bool e)=>Collision=e;public void FaceTarget(in BossPoint p,float r,float d){}public void PlaySpawn(){}public void PlayAttack(){}public void PlayHit(){}public void PlayDeath(){}public void SetAnimationPaused(bool p){}}
    }
}
