using System; using GeneralCore.Architecture; using GameplayCore.Damage; using GameplayCore.Time; using UnityEngine; using ZombieWar.Features.Health.Factories; using ZombieWar.Features.Soldier.Events; using ZombieWar.Features.Targeting.Registry; using ZombieWar.Features.Boss.Catalog; using ZombieWar.Features.Boss.Factories; using ZombieWar.Features.Boss.Registry; using ZombieWar.Features.Boss.Services; using ZombieWar.Features.Boss.Unity.Config;
namespace ZombieWar.Integration.Boss.Unity
{
    [DisallowMultipleComponent]
    public sealed class BossRuntimeRoot:MonoBehaviour
    {
        [SerializeField] private BossCatalogConfig bossCatalogConfig;[SerializeField] private BossPoolRegistry bossPoolRegistry;[SerializeField] private BossSimulationDriver simulationDriver;[SerializeField] private TransformBossTargetSource[] soldierTargets=new TransformBossTargetSource[4];[SerializeField] private MonoBehaviour sharedSoldierGroupDamageableBehaviour;
        private IActiveBossRegistry _active;private IBossSoldierTargetRegistry _soldierRegistry;private IBossAttackBinding _attackBinding;private IBossRuntimeConfigurator _configurator;private IDisposable _soldierAdded;private readonly GameplayCore.Entities.EntityId[] _registeredIds=new GameplayCore.Entities.EntityId[4];private readonly bool[] _registered=new bool[4];public bool IsInitialized{get;private set;}public IBossRuntime Runtime{get;private set;}
        public void Initialize(IBossRuntime runtime,IBossRuntimeConfigurator configurator,IBossFactory factory,IHealthFactory healthFactory,ITargetRegistry targetRegistry,IGameplayClock clock,IBossSoldierTargetRegistry soldierRegistry,IBossAttackBinding attackBinding,IEventSubscriber eventSubscriber)
        {
            if(IsInitialized)return;Runtime=runtime??throw new ArgumentNullException(nameof(runtime));_configurator=configurator??throw new ArgumentNullException(nameof(configurator));if(factory==null)throw new ArgumentNullException(nameof(factory));if(healthFactory==null)throw new ArgumentNullException(nameof(healthFactory));if(targetRegistry==null)throw new ArgumentNullException(nameof(targetRegistry));if(clock==null)throw new ArgumentNullException(nameof(clock));_soldierRegistry=soldierRegistry??throw new ArgumentNullException(nameof(soldierRegistry));_attackBinding=attackBinding??throw new ArgumentNullException(nameof(attackBinding));if(eventSubscriber==null)throw new ArgumentNullException(nameof(eventSubscriber));if(bossCatalogConfig==null)throw new InvalidOperationException("BossCatalogConfig is not assigned.");if(bossPoolRegistry==null)throw new InvalidOperationException("BossPoolRegistry is not assigned.");if(simulationDriver==null)throw new InvalidOperationException("BossSimulationDriver is not assigned.");if(soldierTargets==null||soldierTargets.Length!=4)throw new InvalidOperationException("Exactly four Soldier target sources are required.");for(int i=0;i<4;i++)if(soldierTargets[i]==null)throw new InvalidOperationException($"Soldier target source at slot {i} is not assigned.");
            IBossCatalog catalog=bossCatalogConfig.CreateCatalog();_active=new ActiveBossRegistry();bossPoolRegistry.Initialize(factory,healthFactory,targetRegistry,_active,catalog);simulationDriver.Initialize(_active,clock);_configurator.Initialize(catalog,bossPoolRegistry,_active);_soldierAdded=eventSubscriber.Subscribe<SoldierAddedEvent>(OnSoldierAdded);
            if(sharedSoldierGroupDamageableBehaviour!=null){IDamageable damageable=sharedSoldierGroupDamageableBehaviour as IDamageable;if(damageable==null)throw new InvalidOperationException("Shared Soldier Group damageable Behaviour must implement IDamageable.");_attackBinding.BindSharedSoldierGroup(damageable);}IsInitialized=true;
        }
        public void BindSharedSoldierGroupDamageable(IDamageable damageable)=>_attackBinding?.BindSharedSoldierGroup(damageable); public void SetGameplayEnabled(bool enabled)=>Runtime?.SetGameplayEnabled(enabled); public void CancelAll()=>Runtime?.CancelAll();
        private void OnSoldierAdded(SoldierAddedEvent e){int slot=e.SlotIndex;if(slot<0||slot>=4)return;if(_registered[slot])_soldierRegistry.Unregister(_registeredIds[slot]);_soldierRegistry.Register(e.SoldierId,soldierTargets[slot]);_registeredIds[slot]=e.SoldierId;_registered[slot]=true;}
        private void OnDestroy(){_soldierAdded?.Dispose();Runtime?.CancelAll();if(_soldierRegistry!=null)for(int i=0;i<4;i++)if(_registered[i])_soldierRegistry.Unregister(_registeredIds[i]);_attackBinding?.Unbind();_configurator?.Shutdown();Runtime=null;IsInitialized=false;}
    }
}
