using System; using NUnit.Framework; using ZombieWar.Features.UI.Controller; using ZombieWar.Features.UI.Domain; using ZombieWar.Features.UI.Model; using ZombieWar.Features.UI.Ports; using ZombieWar.Features.UI.Presentation; using ZombieWar.Features.UI.Routing; using ZombieWar.Features.UI.Utilities; using ZombieWar.Features.UI.View;
namespace ZombieWar.Features.UI.Tests
{
    public sealed class UIFeatureTests
    {
        [Test] public void ScreenModel_Initial_None(){var m=new UIScreenModel();Assert.AreEqual(UIScreenId.None,m.Current);}
        [Test] public void Router_Show_Changes(){var r=Router(out var root);Assert.IsTrue(r.Show(UIScreenId.MainMenu));Assert.AreEqual(UIScreenId.MainMenu,r.Current);Assert.IsTrue(root.Main.Visible);}
        [Test] public void Router_Same_ReturnsFalse(){var r=Router(out _);r.Show(UIScreenId.Gameplay);Assert.IsFalse(r.Show(UIScreenId.Gameplay));}
        [Test] public void Router_OnlyOneVisible(){var r=Router(out var root);r.Show(UIScreenId.Pause);Assert.IsTrue(root.PauseV.Visible);Assert.IsFalse(root.Main.Visible);Assert.IsFalse(root.Game.Visible);}
        [Test] public void Router_HideAll(){var r=Router(out var root);r.Show(UIScreenId.GameOver);r.HideAll();Assert.AreEqual(UIScreenId.None,r.Current);Assert.IsFalse(root.Over.Visible);}
        [TestCase(UIScreenId.MainMenu)][TestCase(UIScreenId.Gameplay)][TestCase(UIScreenId.Pause)][TestCase(UIScreenId.LevelComplete)][TestCase(UIScreenId.GameOver)][TestCase(UIScreenId.EndGame)] public void Router_AllScreens(UIScreenId id){var r=Router(out _);Assert.IsTrue(r.Show(id));Assert.AreEqual(id,r.Current);}
        [Test] public void Guard_FirstAccepted(){var g=new SingleExecutionGuard();Assert.IsTrue(g.TryEnter());}
        [Test] public void Guard_SecondRejected(){var g=new SingleExecutionGuard();g.TryEnter();Assert.IsFalse(g.TryEnter());}
        [Test] public void Guard_Reset(){var g=new SingleExecutionGuard();g.TryEnter();g.Reset();Assert.IsTrue(g.TryEnter());}
        [Test] public void MainMenu_Click_PlayOnce(){var flow=new FlowPort();var c=new MainMenuController(flow);var v=new MainView();c.Bind(v);v.ClickPlay();v.ClickPlay();Assert.AreEqual(1,flow.PlayCount);}
        [Test] public void MainMenu_Reset_AllowsAgain(){var flow=new FlowPort();var c=new MainMenuController(flow);var v=new MainView();c.Bind(v);v.ClickPlay();c.Reset();v.ClickPlay();Assert.AreEqual(2,flow.PlayCount);}
        [Test] public void Gameplay_Pause_Forwards(){var pause=new PausePort();var weapons=new WeaponPort();var c=new GameplayHudController(pause,weapons);var v=new GameView();c.Bind(v);v.ClickPause();Assert.AreEqual(1,pause.PauseCount);}
        [TestCase(UIWeaponId.Pistol)][TestCase(UIWeaponId.AK)][TestCase(UIWeaponId.Shotgun)][TestCase(UIWeaponId.SniperRifle)][TestCase(UIWeaponId.GrenadeLauncher)][TestCase(UIWeaponId.Flamethrower)] public void Gameplay_Weapon_Forwards(UIWeaponId id){var p=new PausePort();var wp=new WeaponPort();var c=new GameplayHudController(p,wp);var v=new GameView();c.Bind(v);v.ClickWeapon(id);Assert.AreEqual(id,wp.Last);}
        [Test] public void Pause_Continue_ForwardsResume(){var f=new FlowPort();var p=new PausePort();var c=new PauseController(f,p);var v=new PauseV();c.Bind(v);v.ClickContinue();Assert.AreEqual(1,p.ResumeCount);}
        [Test] public void Pause_Replay_Guarded(){var f=new FlowPort();var p=new PausePort();var c=new PauseController(f,p);var v=new PauseV();c.Bind(v);v.ClickReplay();v.ClickReplay();Assert.AreEqual(1,f.ReplayCount);}
        [Test] public void Pause_Menu_GuardedWithReplay(){var f=new FlowPort();var p=new PausePort();var c=new PauseController(f,p);var v=new PauseV();c.Bind(v);v.ClickReplay();v.ClickMenu();Assert.AreEqual(0,f.MenuCount);}
        [Test] public void Complete_Next_Guarded(){var f=new FlowPort();var c=new LevelCompleteController(f);var v=new CompleteV();c.Bind(v);v.ClickNext();v.ClickReplay();Assert.AreEqual(1,f.NextCount);Assert.AreEqual(0,f.ReplayCount);}
        [Test] public void GameOver_Menu(){var f=new FlowPort();var c=new GameOverController(f);var v=new OverV();c.Bind(v);v.ClickMenu();Assert.AreEqual(1,f.MenuCount);}
        [Test] public void EndGame_Replay(){var f=new FlowPort();var c=new EndGameController(f);var v=new EndV();c.Bind(v);v.ClickReplay();Assert.AreEqual(1,f.ReplayCount);}
        [Test] public void ScorePresenter_RendersHudAndEnd(){var m=new GameplayHudModel();var p=new ScorePresenter(m);var h=new GameView();var e=new EndV();p.Bind(h,e);p.Present(1234);Assert.AreEqual(1234,h.Score);Assert.AreEqual(1234,e.Score);}
        [Test] public void ScorePresenter_ClampsNegative(){var m=new GameplayHudModel();var p=new ScorePresenter(m);p.Present(-1);Assert.AreEqual(0,p.Score);}
        [TestCase(-1f,0f)][TestCase(0f,0f)][TestCase(.5f,.5f)][TestCase(1f,1f)][TestCase(2f,1f)] public void HealthPresenter_Clamp(float value,float expected){var m=new GameplayHudModel();var p=new HealthPresenter(m);var v=new GameView();p.Bind(v);p.Present(value,10,20);Assert.AreEqual(expected,v.Health);}
        [Test] public void LevelPresenter_Renders(){var m=new GameplayHudModel();var p=new LevelPresenter(m);var v=new GameView();p.Bind(v);p.Present(2,4);Assert.AreEqual(2,v.Level);Assert.AreEqual(4,v.GroupLevel);}
        [TestCase(UIWeaponId.Pistol)][TestCase(UIWeaponId.AK)][TestCase(UIWeaponId.Shotgun)][TestCase(UIWeaponId.SniperRifle)][TestCase(UIWeaponId.GrenadeLauncher)][TestCase(UIWeaponId.Flamethrower)] public void WeaponPresenter_SelectsExactlyRequested(UIWeaponId id){var m=new GameplayHudModel();var p=new WeaponHudPresenter(m);var v=new GameView();p.Bind(v);p.PresentSelected(id);Assert.AreEqual(id,v.Selected);}
        [Test] public void WeaponPresenter_ClampsCooldown(){var m=new GameplayHudModel();var p=new WeaponHudPresenter(m);var v=new GameView();p.Bind(v);p.PresentWeapon(UIWeaponId.AK,2f,true);Assert.AreEqual(1f,v.Cooldown);}
        [Test] public void Router_EventOnceAccepted(){var r=Router(out _);int count=0;r.ScreenChanged+=_=>count++;r.Show(UIScreenId.Gameplay);Assert.AreEqual(1,count);}
        [Test] public void Router_NoEventSame(){var r=Router(out _);r.Show(UIScreenId.Gameplay);int count=0;r.ScreenChanged+=_=>count++;r.Show(UIScreenId.Gameplay);Assert.AreEqual(0,count);}
        [Test] public void Runtime_Binds(){var flow=new FlowPort();var pause=new PausePort();var weaponPort=new WeaponPort();var model=new GameplayHudModel();var screenModel=new UIScreenModel();var router=new UIScreenRouter(screenModel);var rt=new ZombieWar.Features.UI.Services.UIRuntime(router,new MainMenuController(flow),new GameplayHudController(pause,weaponPort),new PauseController(flow,pause),new LevelCompleteController(flow),new GameOverController(flow),new EndGameController(flow),new ScorePresenter(model),new HealthPresenter(model),new LevelPresenter(model),new WeaponHudPresenter(model));var root=new Root();rt.Bind(root);Assert.IsTrue(rt.IsBound);rt.Unbind(root);Assert.IsFalse(rt.IsBound);}
        private static UIScreenRouter Router(out Root root){var r=new UIScreenRouter(new UIScreenModel());root=new Root();r.Bind(root);return r;}
        private sealed class FlowPort:IUIFlowActionPort{public int PlayCount,ReplayCount,NextCount,MenuCount;public void Play()=>PlayCount++;public void Replay()=>ReplayCount++;public void Next()=>NextCount++;public void Menu()=>MenuCount++;}
        private sealed class PausePort:IGameplayPausePort{public int PauseCount,ResumeCount;public void Pause()=>PauseCount++;public void Resume()=>ResumeCount++;}
        private sealed class WeaponPort:IWeaponSelectionPort{public UIWeaponId Last;public void Select(UIWeaponId w)=>Last=w;}
        private class Screen:IUIScreenView{public virtual UIScreenId ScreenId=>UIScreenId.None;public bool Visible;public void SetVisible(bool v)=>Visible=v;}
        private sealed class MainView:Screen,IMainMenuView{public override UIScreenId ScreenId=>UIScreenId.MainMenu;public event Action PlayClicked;public void ClickPlay()=>PlayClicked?.Invoke();public void SetTitle(string t){} }
        private sealed class GameView:Screen,IGameplayHudView{public override UIScreenId ScreenId=>UIScreenId.Gameplay;public event Action PauseClicked;public event Action<UIWeaponId> WeaponClicked;public long Score;public int Level,GroupLevel;public float Health,Cooldown;public UIWeaponId Selected;public void ClickPause()=>PauseClicked?.Invoke();public void ClickWeapon(UIWeaponId id)=>WeaponClicked?.Invoke(id);public void SetScore(long s)=>Score=s;public void SetGameLevel(int l)=>Level=l;public void SetSoldierGroupLevel(int l)=>GroupLevel=l;public void SetHealth(float n,float c,float m)=>Health=n;public void SetWeaponState(UIWeaponId w,bool s,float c,bool i){if(s)Selected=w;if(w==UIWeaponId.AK)Cooldown=c;} }
        private sealed class PauseV:Screen,IPauseView{public override UIScreenId ScreenId=>UIScreenId.Pause;public event Action ReplayClicked,ContinueClicked,MenuClicked;public void ClickReplay()=>ReplayClicked?.Invoke();public void ClickContinue()=>ContinueClicked?.Invoke();public void ClickMenu()=>MenuClicked?.Invoke();}
        private sealed class CompleteV:Screen,ILevelCompleteView{public override UIScreenId ScreenId=>UIScreenId.LevelComplete;public event Action ReplayClicked,NextClicked,MenuClicked;public void ClickReplay()=>ReplayClicked?.Invoke();public void ClickNext()=>NextClicked?.Invoke();public void ClickMenu()=>MenuClicked?.Invoke();}
        private sealed class OverV:Screen,IGameOverView{public override UIScreenId ScreenId=>UIScreenId.GameOver;public event Action ReplayClicked,MenuClicked;public void ClickReplay()=>ReplayClicked?.Invoke();public void ClickMenu()=>MenuClicked?.Invoke();}
        private sealed class EndV:Screen,IEndGameView{public override UIScreenId ScreenId=>UIScreenId.EndGame;public event Action ReplayClicked,MenuClicked;public long Score;public void ClickReplay()=>ReplayClicked?.Invoke();public void ClickMenu()=>MenuClicked?.Invoke();public void SetFinalScore(long s)=>Score=s;public void SetReplayVisible(bool v){} }
        private sealed class Root:IUIRootView{public readonly MainView Main=new MainView();public readonly GameView Game=new GameView();public readonly PauseV PauseV=new PauseV();public readonly CompleteV Complete=new CompleteV();public readonly OverV Over=new OverV();public readonly EndV End=new EndV();public IMainMenuView MainMenu=>Main;public IGameplayHudView Gameplay=>Game;public IPauseView Pause=>PauseV;public ILevelCompleteView LevelComplete=>Complete;public IGameOverView GameOver=>Over;public IEndGameView EndGame=>End;}
    }
}
