using System;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace ZombieWar.Features.Zombie.Editor
{
    /// <summary>
    /// Editor-only builder for the Zombie presentation Animator Controller.
    ///
    /// This tool intentionally owns only generated Animator assets. It does not
    /// change Zombie AI, attack timing, damage, pooling, runtime state, or any
    /// gameplay code.
    /// </summary>
    public sealed class ZombieAnimatorBuilderWindow : EditorWindow
    {
        private const string DefaultOutputFolder =
            "Assets/Game/Generated/ZombieAnimation";

        private const string ControllerFileName =
            "ZombieWar_Zombie.controller";

        public const string MovementSpeedParameter =
            "ZombieMovementSpeed";

        // Presentation trigger convention generated by this tool.
        // Runtime wiring must drive these exact names (or the tool/runtime
        // contract must be changed together).
        public const string AttackParameter = "Attack";
        public const string HitParameter = "Hit";
        public const string DeathParameter = "Death";

        [SerializeField]
        private AnimationClip idleClip;

        [SerializeField]
        private AnimationClip walkClip;

        [SerializeField]
        private AnimationClip runClip;

        [SerializeField]
        private AnimationClip attackClip;

        [SerializeField]
        private AnimationClip hitClip;

        [SerializeField]
        private AnimationClip deathClip;

        [SerializeField]
        private string outputFolder = DefaultOutputFolder;

        [SerializeField]
        [Range(0.01f, 0.3f)]
        private float attackTransitionDuration = 0.08f;

        [SerializeField]
        [Range(0.01f, 0.3f)]
        private float hitTransitionDuration = 0.06f;

        [MenuItem("Tools/Zombie War/Zombie/Open Animator Builder")]
        public static void Open()
        {
            var window = GetWindow<ZombieAnimatorBuilderWindow>();
            window.titleContent = new GUIContent("Zombie Animator");
            window.minSize = new Vector2(430f, 500f);
            window.Show();
        }

        private void OnGUI()
        {
            EditorGUILayout.Space(8f);
            EditorGUILayout.LabelField(
                "Zombie Animator Builder",
                EditorStyles.boldLabel);

            EditorGUILayout.HelpBox(
                "Builds one Animator Controller with a 1D locomotion Blend Tree " +
                "and Attack / Hit / Death states. Root Motion must remain OFF on " +
                "the Zombie Animator component.",
                MessageType.Info);

            EditorGUILayout.Space(6f);
            EditorGUILayout.LabelField("Locomotion Clips", EditorStyles.boldLabel);

            idleClip = (AnimationClip)EditorGUILayout.ObjectField(
                "Idle (Required)",
                idleClip,
                typeof(AnimationClip),
                false);

            walkClip = (AnimationClip)EditorGUILayout.ObjectField(
                "Walk (Optional)",
                walkClip,
                typeof(AnimationClip),
                false);

            runClip = (AnimationClip)EditorGUILayout.ObjectField(
                "Run (Required)",
                runClip,
                typeof(AnimationClip),
                false);

            EditorGUILayout.Space(6f);
            EditorGUILayout.LabelField("Action Clips", EditorStyles.boldLabel);

            attackClip = (AnimationClip)EditorGUILayout.ObjectField(
                "Attack (Required)",
                attackClip,
                typeof(AnimationClip),
                false);

            hitClip = (AnimationClip)EditorGUILayout.ObjectField(
                "Hit (Required)",
                hitClip,
                typeof(AnimationClip),
                false);

            deathClip = (AnimationClip)EditorGUILayout.ObjectField(
                "Death (Required)",
                deathClip,
                typeof(AnimationClip),
                false);

            EditorGUILayout.Space(8f);
            EditorGUILayout.LabelField("Generated Asset", EditorStyles.boldLabel);

            outputFolder = EditorGUILayout.TextField(
                "Output Folder",
                outputFolder);

            attackTransitionDuration = EditorGUILayout.Slider(
                "Attack Transition",
                attackTransitionDuration,
                0.01f,
                0.3f);

            hitTransitionDuration = EditorGUILayout.Slider(
                "Hit Transition",
                hitTransitionDuration,
                0.01f,
                0.3f);

            EditorGUILayout.Space(8f);
            DrawGeneratedContract();

            EditorGUILayout.Space(12f);

            using (new EditorGUI.DisabledScope(!HasRequiredClips()))
            {
                if (GUILayout.Button(
                        "Build / Rebuild Zombie Animator",
                        GUILayout.Height(34f)))
                {
                    Build();
                }
            }

            if (!HasRequiredClips())
            {
                EditorGUILayout.HelpBox(
                    "Assign Idle, Run, Attack, Hit and Death clips. Walk is optional.",
                    MessageType.Warning);
            }
        }

        private void DrawGeneratedContract()
        {
            EditorGUILayout.HelpBox(
                "Generated parameters:\n" +
                "• ZombieMovementSpeed (Float)\n" +
                "• Attack (Trigger)\n" +
                "• Hit (Trigger)\n" +
                "• Death (Trigger)\n\n" +
                "Locomotion thresholds:\n" +
                (walkClip != null
                    ? "• 0.0 Idle / 0.5 Walk / 1.0 Run"
                    : "• 0.0 Idle / 1.0 Run"),
                MessageType.None);
        }

        private bool HasRequiredClips()
        {
            return idleClip != null &&
                   runClip != null &&
                   attackClip != null &&
                   hitClip != null &&
                   deathClip != null;
        }

        private void Build()
        {
            if (!HasRequiredClips())
            {
                EditorUtility.DisplayDialog(
                    "Zombie Animator",
                    "Assign all required clips before building.",
                    "OK");
                return;
            }

            string normalizedFolder = NormalizeOutputFolder(outputFolder);
            EnsureFolderExists(normalizedFolder);

            string controllerPath =
                normalizedFolder + "/" + ControllerFileName;

            AnimatorController controller =
                AssetDatabase.LoadAssetAtPath<AnimatorController>(controllerPath);

            if (controller == null)
            {
                controller =
                    AnimatorController.CreateAnimatorControllerAtPath(
                        controllerPath);
            }

            if (controller == null)
            {
                throw new InvalidOperationException(
                    "Could not create Zombie Animator Controller at: " +
                    controllerPath);
            }

            RebuildController(controller);

            EditorUtility.SetDirty(controller);
            AssetDatabase.SaveAssets();
            AssetDatabase.ImportAsset(controllerPath);
            AssetDatabase.Refresh();

            Selection.activeObject = controller;
            EditorGUIUtility.PingObject(controller);

            EditorUtility.DisplayDialog(
                "Zombie Animator",
                "Zombie Animator Controller built successfully:\n\n" +
                controllerPath,
                "OK");
        }

        private void RebuildController(
            AnimatorController controller)
        {
            ClearParameters(controller);

            controller.AddParameter(
                MovementSpeedParameter,
                AnimatorControllerParameterType.Float);
            controller.AddParameter(
                AttackParameter,
                AnimatorControllerParameterType.Trigger);
            controller.AddParameter(
                HitParameter,
                AnimatorControllerParameterType.Trigger);
            controller.AddParameter(
                DeathParameter,
                AnimatorControllerParameterType.Trigger);

            AnimatorStateMachine stateMachine =
                GetOrCreateBaseStateMachine(controller);

            ClearStateMachine(stateMachine);
            RemoveGeneratedBlendTrees(controller);

            AnimatorState locomotionState = stateMachine.AddState(
                "Locomotion",
                new Vector3(320f, 140f, 0f));

            BlendTree locomotionTree = CreateLocomotionBlendTree(controller);
            locomotionState.motion = locomotionTree;
            stateMachine.defaultState = locomotionState;

            AnimatorState attackState = stateMachine.AddState(
                "Attack",
                new Vector3(590f, 40f, 0f));
            attackState.motion = attackClip;

            AnimatorState hitState = stateMachine.AddState(
                "Hit",
                new Vector3(590f, 140f, 0f));
            hitState.motion = hitClip;

            AnimatorState deathState = stateMachine.AddState(
                "Death",
                new Vector3(590f, 250f, 0f));
            deathState.motion = deathClip;

            // Priority is intentional: terminal Death first, then Hit, then Attack.
            AddAnyStateTriggerTransition(
                stateMachine,
                deathState,
                DeathParameter,
                0.04f);

            AddAnyStateTriggerTransition(
                stateMachine,
                hitState,
                HitParameter,
                hitTransitionDuration);

            AddAnyStateTriggerTransition(
                stateMachine,
                attackState,
                AttackParameter,
                attackTransitionDuration);

            AddReturnToLocomotionTransition(
                attackState,
                locomotionState,
                attackTransitionDuration);

            AddReturnToLocomotionTransition(
                hitState,
                locomotionState,
                hitTransitionDuration);
        }

        private BlendTree CreateLocomotionBlendTree(
            AnimatorController controller)
        {
            var blendTree = new BlendTree
            {
                name = "Zombie Locomotion Blend Tree",
                blendType = BlendTreeType.Simple1D,
                blendParameter = MovementSpeedParameter,
                useAutomaticThresholds = false,
                hideFlags = HideFlags.HideInHierarchy
            };

            AssetDatabase.AddObjectToAsset(blendTree, controller);

            blendTree.AddChild(idleClip, 0f);

            if (walkClip != null)
            {
                blendTree.AddChild(walkClip, 0.5f);
            }

            blendTree.AddChild(runClip, 1f);
            EditorUtility.SetDirty(blendTree);

            return blendTree;
        }

        private static AnimatorStateMachine GetOrCreateBaseStateMachine(
            AnimatorController controller)
        {
            AnimatorControllerLayer[] layers = controller.layers;

            if (layers != null && layers.Length > 0)
            {
                AnimatorControllerLayer baseLayer = layers[0];
                baseLayer.name = "Base Layer";
                baseLayer.defaultWeight = 1f;

                if (baseLayer.stateMachine == null)
                {
                    var stateMachine = new AnimatorStateMachine
                    {
                        name = "Base Layer"
                    };
                    AssetDatabase.AddObjectToAsset(stateMachine, controller);
                    baseLayer.stateMachine = stateMachine;
                }

                controller.layers = new[] { baseLayer };
                return baseLayer.stateMachine;
            }

            var createdStateMachine = new AnimatorStateMachine
            {
                name = "Base Layer"
            };
            AssetDatabase.AddObjectToAsset(createdStateMachine, controller);

            controller.layers = new[]
            {
                new AnimatorControllerLayer
                {
                    name = "Base Layer",
                    defaultWeight = 1f,
                    stateMachine = createdStateMachine
                }
            };

            return createdStateMachine;
        }

        private static void ClearParameters(
            AnimatorController controller)
        {
            AnimatorControllerParameter[] parameters = controller.parameters;

            for (int i = parameters.Length - 1; i >= 0; i--)
            {
                controller.RemoveParameter(i);
            }
        }

        private static void ClearStateMachine(
            AnimatorStateMachine stateMachine)
        {
            ChildAnimatorState[] states = stateMachine.states;
            for (int i = states.Length - 1; i >= 0; i--)
            {
                stateMachine.RemoveState(states[i].state);
            }

            ChildAnimatorStateMachine[] childMachines =
                stateMachine.stateMachines;
            for (int i = childMachines.Length - 1; i >= 0; i--)
            {
                stateMachine.RemoveStateMachine(
                    childMachines[i].stateMachine);
            }

            AnimatorStateTransition[] anyTransitions =
                stateMachine.anyStateTransitions;
            for (int i = anyTransitions.Length - 1; i >= 0; i--)
            {
                stateMachine.RemoveAnyStateTransition(anyTransitions[i]);
            }

            AnimatorTransition[] entryTransitions =
                stateMachine.entryTransitions;
            for (int i = entryTransitions.Length - 1; i >= 0; i--)
            {
                stateMachine.RemoveEntryTransition(entryTransitions[i]);
            }
        }

        private static void RemoveGeneratedBlendTrees(
            AnimatorController controller)
        {
            UnityEngine.Object[] assets =
                AssetDatabase.LoadAllAssetsAtPath(
                    AssetDatabase.GetAssetPath(controller));

            for (int i = assets.Length - 1; i >= 0; i--)
            {
                if (assets[i] is BlendTree blendTree &&
                    blendTree.name == "Zombie Locomotion Blend Tree")
                {
                    DestroyImmediate(blendTree, true);
                }
            }
        }

        private static void AddAnyStateTriggerTransition(
            AnimatorStateMachine stateMachine,
            AnimatorState destination,
            string triggerParameter,
            float duration)
        {
            AnimatorStateTransition transition =
                stateMachine.AddAnyStateTransition(destination);

            transition.hasExitTime = false;
            transition.hasFixedDuration = true;
            transition.duration = duration;
            transition.canTransitionToSelf = false;
            transition.interruptionSource =
                TransitionInterruptionSource.None;
            transition.AddCondition(
                AnimatorConditionMode.If,
                0f,
                triggerParameter);
        }

        private static void AddReturnToLocomotionTransition(
            AnimatorState source,
            AnimatorState locomotion,
            float duration)
        {
            AnimatorStateTransition transition =
                source.AddTransition(locomotion);

            transition.hasExitTime = true;
            transition.exitTime = 0.95f;
            transition.hasFixedDuration = true;
            transition.duration = duration;
            transition.interruptionSource =
                TransitionInterruptionSource.None;
        }

        private static string NormalizeOutputFolder(
            string folder)
        {
            if (string.IsNullOrWhiteSpace(folder))
            {
                return DefaultOutputFolder;
            }

            string normalized = folder.Trim().Replace('\\', '/');

            while (normalized.EndsWith("/", StringComparison.Ordinal))
            {
                normalized = normalized.Substring(0, normalized.Length - 1);
            }

            if (!normalized.StartsWith("Assets/", StringComparison.Ordinal) &&
                !string.Equals(normalized, "Assets", StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    "Zombie Animator output folder must be inside Assets/. " +
                    "Current value: " + normalized);
            }

            return normalized;
        }

        private static void EnsureFolderExists(
            string folder)
        {
            if (AssetDatabase.IsValidFolder(folder))
            {
                return;
            }

            string[] parts = folder.Split('/');
            if (parts.Length == 0 || parts[0] != "Assets")
            {
                throw new InvalidOperationException(
                    "Output folder must be inside Assets/. " + folder);
            }

            string current = "Assets";

            for (int i = 1; i < parts.Length; i++)
            {
                string next = current + "/" + parts[i];

                if (!AssetDatabase.IsValidFolder(next))
                {
                    AssetDatabase.CreateFolder(current, parts[i]);
                }

                current = next;
            }
        }
    }
}
