using System; using GeneralCore.Architecture; using GameplayCore.Damage; using GameplayCore.Entities; using ZombieWar.Features.Boss.Domain; using ZombieWar.Features.Boss.Events; using ZombieWar.Features.Boss.Model; using ZombieWar.Features.Boss.Ports; using ZombieWar.Features.Boss.StateMachine; using ZombieWar.Features.Boss.Strategies;
namespace ZombieWar.Features.Boss.Controller
{
    public sealed class BossController:IController
    {
        private readonly IEntityIdGenerator _ids; private readonly BossModel _model; private readonly IBossView _view; private readonly IBossMotor _motor; private readonly IBossHealthPort _health; private readonly IBossTargetRegistrationPort _registration; private readonly IBossPoolReturnPort _poolReturn; private readonly IBossFeedbackPort _feedback; private readonly IEventBus _events; private readonly BossStateMachine _machine; private readonly AttackBossState _attack; private readonly HitBossState _hit; private readonly DeathBossState _death;
        public EntityId EntityId=>_model.EntityId; public BossId BossId=>_model.IsActive?_model.Definition.Id:BossId.None; public BossStateId State=>_model.State; public bool IsActive=>_model.IsActive; public bool IsAlive=>_model.IsActive&&_model.State!=BossStateId.Death&&_health.IsAlive; public bool IsTargetable=>IsAlive&&_model.IsTargetable; public bool GameplayEnabled=>_model.GameplayEnabled; public BossPoint Position=>_view.Position; public float CurrentHealth=>_health.CurrentHealth; public float MaxHealth=>_health.MaxHealth;
        public BossController(IEntityIdGenerator ids,BossModel model,IBossView view,IBossMotor motor,IBossHealthPort health,IBossTargetProvider targetProvider,IBossAttackStrategy attackStrategy,IBossTargetRegistrationPort registration,IBossPoolReturnPort poolReturn,IBossFeedbackPort feedback,IEventBus events)
        {
            _ids=ids??throw new ArgumentNullException(nameof(ids));_model=model??throw new ArgumentNullException(nameof(model));_view=view??throw new ArgumentNullException(nameof(view));_motor=motor??throw new ArgumentNullException(nameof(motor));_health=health??throw new ArgumentNullException(nameof(health));_registration=registration??throw new ArgumentNullException(nameof(registration));_poolReturn=poolReturn??throw new ArgumentNullException(nameof(poolReturn));_feedback=feedback??NullBossFeedbackPort.Instance;_events=events??throw new ArgumentNullException(nameof(events));
            var c=new BossStateContext(_model,_view,_motor,targetProvider??throw new ArgumentNullException(nameof(targetProvider)),attackStrategy??throw new ArgumentNullException(nameof(attackStrategy)),_registration,_poolReturn,_feedback,_events,ChangeState);
            _machine=new BossStateMachine();_machine.Register(new SpawnBossState(c));_machine.Register(new ChaseBossState(c));_attack=new AttackBossState(c);_hit=new HitBossState(c);_death=new DeathBossState(c);_machine.Register(_attack);_machine.Register(_hit);_machine.Register(_death);
        }
        public EntityId Activate(in BossDefinition definition,in BossSpawnRequest request)
        {
            if(_model.IsActive)throw new InvalidOperationException("Boss is already active.");if(definition.Id!=request.BossId)throw new ArgumentException("BossDefinition and BossSpawnRequest IDs must match.");
            EntityId id=_ids.Next();_model.Activate(id,in definition);_death.ResetForReuse();_health.Initialize(id,definition.MaxHealth);_view.ResetForReuse();_view.SetScale(definition.Scale);_view.SetActive(true);_view.SetAnimationPaused(false);_view.SetGameplayCollisionEnabled(true);BossPoint p=request.Position;_motor.Warp(in p);_motor.SetEnabled(true);_registration.Register(id);_events.Publish(new BossActivatedEvent(definition.Id,id));_machine.Change(BossStateId.Spawn);return id;
        }
        public void Tick(float dt){if(!_model.IsActive||dt<0f||!_model.GameplayEnabled)return;_model.TickTimers(dt);_machine.Tick(dt);}
        public void SetGameplayEnabled(bool enabled){if(!_model.IsActive||_model.GameplayEnabled==enabled)return;_model.SetGameplayEnabled(enabled);_view.SetAnimationPaused(!enabled);_motor.SetEnabled(enabled&&_model.State!=BossStateId.Death);if(!enabled){_motor.Stop();_view.SetLocomotionSpeed(0f);}}
        public void ReceiveDamage(DamageInfo damage){if(!IsAlive||damage.Amount<=0f)return;_model.SetLastDamageSource(damage.Source);_health.ApplyDamage(damage);if(!_health.IsAlive){ChangeState(BossStateId.Death);return;}BossPoint p=_view.Position;_feedback.OnHit(_model.Definition.Id,_model.EntityId,in p);if(_model.CanStartHitReaction&&_model.State!=BossStateId.Spawn&&_model.State!=BossStateId.Death)ChangeState(BossStateId.Hit);}
        public void NotifyAttackImpact(){if(_model.State==BossStateId.Attack)_attack.OnAttackImpact();} public void NotifyAttackAnimationFinished(){if(_model.State==BossStateId.Attack)_attack.OnAttackAnimationFinished();} public void NotifyHitAnimationFinished(){if(_model.State==BossStateId.Hit)_hit.Finish();} public void NotifyDeathAnimationFinished(){if(_model.State==BossStateId.Death)_death.OnDeathAnimationFinished();}
        public void Cancel(){if(!_model.IsActive||_model.ReturnRequested)return;BossId bossId=_model.Definition.Id;EntityId id=_model.EntityId;_model.SetTargetable(false);_model.ClearTarget();_registration.Unregister(id);_motor.Stop();_motor.SetEnabled(false);_view.SetGameplayCollisionEnabled(false);_model.MarkReturnRequested();_events.Publish(new BossReleasedEvent(bossId,id,BossReleaseReason.Cancelled));_poolReturn.Return(id,BossReleaseReason.Cancelled);}
        public void DeactivateForPool(){if(!_model.IsActive)return;EntityId id=_model.EntityId;_registration.Unregister(id);_machine.Clear();_motor.Stop();_motor.SetEnabled(false);_view.SetGameplayCollisionEnabled(false);_view.SetAnimationPaused(false);_view.SetActive(false);_model.Deactivate();}
        private void ChangeState(BossStateId id){if(!_model.IsActive||(_model.State==BossStateId.Death&&id!=BossStateId.Death))return;_machine.Change(id);}
    }
}
