#if UNITY_EDITOR
using TMPro; using UnityEditor; using UnityEngine; using UnityEngine.EventSystems; using UnityEngine.UI; using ZombieWar.Features.UI.Domain; using ZombieWar.Features.UI.Unity.Components; using ZombieWar.Features.UI.Unity.Root; using ZombieWar.Features.UI.Unity.Views;
namespace ZombieWar.Features.UI.Editor
{
    public static class ZombieWarUIPlaceholderBuilder
    {
        [MenuItem("Tools/Zombie War/UI/Create Placeholder UI Root")]
        public static void Create()
        {
            if(Object.FindFirstObjectByType<UIRuntimeRoot>()!=null){Selection.activeObject=Object.FindFirstObjectByType<UIRuntimeRoot>().gameObject;Debug.Log("[ZombieWar UI] UIRuntimeRoot already exists.");return;}
            var root=new GameObject("ZombieWar_UIRoot",typeof(RectTransform),typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster),typeof(UIRuntimeRoot));
            var canvas=root.GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;
            var scaler=root.GetComponent<CanvasScaler>();scaler.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new Vector2(1080,1920);scaler.matchWidthOrHeight=.5f;
            EnsureEventSystem();
            var main=BuildMainMenu(root.transform); var hud=BuildHud(root.transform); var pause=BuildPause(root.transform); var complete=BuildComplete(root.transform); var over=BuildGameOver(root.transform); var end=BuildEnd(root.transform);
            Assign(root.GetComponent<UIRuntimeRoot>(),"mainMenu",main,"gameplay",hud,"pause",pause,"levelComplete",complete,"gameOver",over,"endGame",end);
            main.SetVisible(false);hud.SetVisible(false);pause.SetVisible(false);complete.SetVisible(false);over.SetVisible(false);end.SetVisible(false);
            Selection.activeGameObject=root;Undo.RegisterCreatedObjectUndo(root,"Create ZombieWar UI Root");Debug.Log("[ZombieWar UI] Placeholder UIRoot created. Bind it to IUIRuntime from your scene composition root.");
        }
        private static MainMenuView BuildMainMenu(Transform p){var go=Screen("MainMenuScreen",p);var v=go.AddComponent<MainMenuView>();var bg=CreateImage("Background",go.transform,true);var safe=Safe(go.transform);var title=Text("ZOMBIE WAR",safe,72,new Vector2(0,260));var play=Button("PLAY",safe,new Vector2(0,-100),new Vector2(360,120));Assign(v,"canvasGroup",go.GetComponent<CanvasGroup>(),"playButton",play,"titleText",title,"background",bg);return v;}
        private static GameplayHudView BuildHud(Transform p){var go=Screen("GameplayHUD",p);var v=go.AddComponent<GameplayHudView>();var safe=Safe(go.transform);var hpBg=CreateImage("HP",safe,false);Rect(hpBg.rectTransform,new Vector2(.04f,.9f),new Vector2(.38f,.965f));var hpFill=CreateImage("Fill",hpBg.transform,false);Stretch(hpFill.rectTransform);hpFill.type=Image.Type.Filled;hpFill.fillMethod=Image.FillMethod.Horizontal;var hpText=Text("-- / --",hpBg.transform,24,Vector2.zero);Stretch(hpText.rectTransform);var score=Text("SCORE  0",safe,32,new Vector2(0,0));Rect(score.rectTransform,new Vector2(.38f,.91f),new Vector2(.62f,.97f));var level=Text("LEVEL -",safe,28,Vector2.zero);Rect(level.rectTransform,new Vector2(.65f,.91f),new Vector2(.79f,.97f));var group=Text("GROUP Lv.-",safe,22,Vector2.zero);Rect(group.rectTransform,new Vector2(.65f,.86f),new Vector2(.82f,.91f));var pause=Button("II",safe,new Vector2(0,0),new Vector2(100,100));Rect(pause.GetComponent<RectTransform>(),new Vector2(.84f,.89f),new Vector2(.96f,.97f));var bar=new GameObject("WeaponBar",typeof(RectTransform),typeof(HorizontalLayoutGroup),typeof(ResponsiveGameplayHudLayout));bar.transform.SetParent(safe,false);var br=(RectTransform)bar.transform;br.anchorMin=new Vector2(.5f,0);br.anchorMax=new Vector2(.5f,0);br.pivot=new Vector2(.5f,0);br.anchoredPosition=new Vector2(0,40);br.sizeDelta=new Vector2(900,120);var layout=bar.GetComponent<HorizontalLayoutGroup>();layout.spacing=12;layout.childForceExpandWidth=true;layout.childForceExpandHeight=true;var buttons=new WeaponButtonView[6];string[] names={"Pistol","AK","Shotgun","Sniper","Grenade","Flame"};for(int i=0;i<6;i++)buttons[i]=WeaponButton(names[i],(UIWeaponId)i,bar.transform);
            Assign(v,"canvasGroup",go.GetComponent<CanvasGroup>(),"scoreText",score,"levelText",level,"groupLevelText",group,"healthText",hpText,"healthFill",hpFill,"pauseButton",pause,"weaponButtons",buttons); return v;}
        private static PauseView BuildPause(Transform p){var go=Modal("PauseScreen",p,"PAUSED",out var panel);var v=go.AddComponent<PauseView>();var r=Button("REPLAY",panel,new Vector2(0,80),new Vector2(360,90));var c=Button("CONTINUE",panel,new Vector2(0,-30),new Vector2(360,90));var m=Button("MENU",panel,new Vector2(0,-140),new Vector2(360,90));Assign(v,"canvasGroup",go.GetComponent<CanvasGroup>(),"replayButton",r,"continueButton",c,"menuButton",m);return v;}
        private static LevelCompleteView BuildComplete(Transform p){var go=Modal("LevelCompleteScreen",p,"LEVEL COMPLETE",out var panel);var v=go.AddComponent<LevelCompleteView>();var r=Button("REPLAY",panel,new Vector2(0,80),new Vector2(340,86));var n=Button("NEXT",panel,new Vector2(0,-25),new Vector2(340,86));var m=Button("MENU",panel,new Vector2(0,-130),new Vector2(340,86));Assign(v,"canvasGroup",go.GetComponent<CanvasGroup>(),"replayButton",r,"nextButton",n,"menuButton",m);return v;}
        private static GameOverView BuildGameOver(Transform p){var go=Modal("GameOverScreen",p,"GAME OVER",out var panel);var v=go.AddComponent<GameOverView>();var r=Button("REPLAY",panel,new Vector2(0,25),new Vector2(340,90));var m=Button("MENU",panel,new Vector2(0,-95),new Vector2(340,90));Assign(v,"canvasGroup",go.GetComponent<CanvasGroup>(),"replayButton",r,"menuButton",m);return v;}
        private static EndGameView BuildEnd(Transform p){var go=Modal("EndGameScreen",p,"YOU SURVIVED",out var panel);var v=go.AddComponent<EndGameView>();var final=Text("FINAL SCORE\n0",panel,34,new Vector2(0,95));var r=Button("REPLAY",panel,new Vector2(0,-15),new Vector2(340,85));var m=Button("MENU",panel,new Vector2(0,-120),new Vector2(340,85));Assign(v,"canvasGroup",go.GetComponent<CanvasGroup>(),"replayButton",r,"menuButton",m,"finalScoreText",final);return v;}
        private static GameObject Screen(string n,Transform p){var go=new GameObject(n,typeof(RectTransform),typeof(CanvasGroup));go.transform.SetParent(p,false);Stretch((RectTransform)go.transform);return go;} private static GameObject Modal(string n,Transform p,string title,out Transform panel){var go=Screen(n,p);var blocker=CreateImage("Blocker",go.transform,false);Stretch(blocker.rectTransform);blocker.color=new Color(0,0,0,.65f);var po=CreateImage("Panel",go.transform,false);var rt=po.rectTransform;rt.anchorMin=rt.anchorMax=new Vector2(.5f,.5f);rt.sizeDelta=new Vector2(620,700);panel=po.transform;Text(title,panel,48,new Vector2(0,240));return go;}
        private static Transform Safe(Transform p){var go=new GameObject("SafeArea",typeof(RectTransform),typeof(SafeAreaView));go.transform.SetParent(p,false);Stretch((RectTransform)go.transform);return go.transform;}
        private static WeaponButtonView WeaponButton(string text,UIWeaponId id,Transform p){var b=Button(text,p,Vector2.zero,new Vector2(130,110));var v=b.gameObject.AddComponent<WeaponButtonView>();var cool=CreateImage("Cooldown",b.transform,false);Stretch(cool.rectTransform);cool.type=Image.Type.Filled;cool.fillMethod=Image.FillMethod.Radial360;cool.fillAmount=0;cool.raycastTarget=false;var sel=CreateImage("Selected",b.transform,false);Stretch(sel.rectTransform);sel.raycastTarget=false;sel.gameObject.SetActive(false);var label=b.GetComponentInChildren<TMP_Text>();Assign(v,"weapon",id,"button",b,"label",label,"cooldownFill",cool,"selectedIndicator",sel.gameObject);return v;}
        private static Button Button(string text,Transform p,Vector2 pos,Vector2 size){var go=CreateImage(text+"Button",p,false);var rt=go.rectTransform;rt.anchorMin=rt.anchorMax=new Vector2(.5f,.5f);rt.anchoredPosition=pos;rt.sizeDelta=size;var b=go.gameObject.AddComponent<Button>();var t=Text(text,go.transform,28,Vector2.zero);Stretch(t.rectTransform);return b;}
        private static TMP_Text Text(string value,Transform p,float size,Vector2 pos){var go=new GameObject("Text",typeof(RectTransform),typeof(TextMeshProUGUI));go.transform.SetParent(p,false);var t=go.GetComponent<TextMeshProUGUI>();t.text=value;t.fontSize=size;t.alignment=TextAlignmentOptions.Center;t.raycastTarget=false;var rt=(RectTransform)go.transform;rt.anchorMin=rt.anchorMax=new Vector2(.5f,.5f);rt.anchoredPosition=pos;rt.sizeDelta=new Vector2(500,100);return t;}
        private static Image CreateImage(string n,Transform p,bool full){var go=new GameObject(n,typeof(RectTransform),typeof(Image));go.transform.SetParent(p,false);var im=go.GetComponent<Image>();im.color=new Color(.12f,.12f,.15f,.92f);im.raycastTarget=!full;if(full)Stretch(go.GetComponent<RectTransform>());return im;}
        private static void EnsureEventSystem(){if(Object.FindFirstObjectByType<EventSystem>()!=null)return;var go=new GameObject("EventSystem",typeof(EventSystem));var inputSystemType=System.Type.GetType("UnityEngine.InputSystem.UI.InputSystemUIInputModule, Unity.InputSystem");if(inputSystemType!=null)go.AddComponent(inputSystemType);else go.AddComponent<StandaloneInputModule>();}
        private static void Stretch(RectTransform r){r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=Vector2.zero;r.offsetMax=Vector2.zero;} private static void Rect(RectTransform r,Vector2 min,Vector2 max){r.anchorMin=min;r.anchorMax=max;r.offsetMin=Vector2.zero;r.offsetMax=Vector2.zero;}
        private static void Assign(Object target,params object[] pairs){var so=new SerializedObject(target);for(int i=0;i<pairs.Length;i+=2){var p=so.FindProperty((string)pairs[i]);if(p==null)continue;var v=pairs[i+1];if(v is Object o)p.objectReferenceValue=o;else if(v is int iv)p.intValue=iv;else if(v is System.Enum ev)p.enumValueIndex=System.Convert.ToInt32(ev);else if(v is System.Array arr&&p.isArray){p.arraySize=arr.Length;for(int j=0;j<arr.Length;j++)p.GetArrayElementAtIndex(j).objectReferenceValue=arr.GetValue(j) as Object;}}so.ApplyModifiedPropertiesWithoutUndo();}
    }
}
#endif
